"""Content-source candidate filters.

Each filter is a pure function; ``passes`` composes them all and returns
``(ok, rejection_reason)`` so callers can log why a candidate was dropped.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from database.models import FacebookPage


# Heuristic: titles strongly indicating a music compilation / playlist / DJ mix.
# These rarely contain coherent dialogue, so they're useless for shortform
# storytelling pipelines that depend on transcript-driven clip detection.
_MUSIC_PATTERNS = (
    r"\bmusic\b",
    r"\bsongs?\b",
    r"\bplaylist\b",
    r"\bmix(es|tape)?\b",
    r"\bremix(es)?\b",
    r"\blyrics?\b",
    r"\bsoundtrack\b",
    r"\bno copyright\b",
    r"\bofficial (music )?video\b",
    r"\bmv\b",
    r"\bost\b",
    r"\bbeat[s]?\b",
    r"\bedm\b",
    r"\bdj\b",
    r"\bnhạc\b",
    r"\bbản nhạc\b",
    r"\bplaylist gym\b",
)

_MUSIC_RE = re.compile("|".join(_MUSIC_PATTERNS), re.IGNORECASE)


def _looks_like_music(item: dict[str, Any]) -> bool:
    """Detect music-compilation / DJ-mix titles via keyword + categories."""
    title = (item.get("title") or "")
    desc = (item.get("description") or "")[:400]
    haystack = f"{title}\n{desc}"
    if _MUSIC_RE.search(haystack):
        return True
    # YouTube category. ytdlp puts it as 'categories' (list) or similar.
    cats = item.get("categories") or []
    if isinstance(cats, list):
        for c in cats:
            if isinstance(c, str) and c.strip().lower() == "music":
                return True
    if (item.get("category") or "").strip().lower() == "music":
        return True
    return False


# Heuristic: title/description signals indicating AI-generated long-form
# content (synthetic narration, AI animation, story-farm channels). These
# pipelines lack real human dialogue/B-roll and are useless for shortform
# storytelling sourced from authentic creators.
#
# HARD patterns: a single match anywhere in title+description is enough.
# Phrased tightly so they don't fire on tutorial / commentary content that
# merely mentions "AI" in passing (e.g. "ChatGPT Tutorial").
_AI_HARD_PATTERNS = (
    r"\bAI[- ]?generated\b",
    r"\bgenerated by AI\b",
    r"\bgenerated (?:with|using) AI\b",
    r"\bmade (?:with|using|by) AI\b",
    r"\bAI[- ]?narrated\b",
    r"\bnarrated by AI\b",
    r"\bAI[- ]?voiceover\b",
    r"\bAI voice(?:[- ]?over)?\b",
    r"\bAI[- ]?animation\b",
    r"\bAI[- ]?rendered\b",
    r"\bAI[- ]?storyteller\b",
    r"\bAI story\b",
    r"\bChatGPT story\b",
    r"\bGPT[- ]?narrated\b",
    r"\btext[- ]to[- ]speech narration\b",
    # Specific AI tools, but only when the phrasing tags them as the
    # producer (e.g. "Made with Midjourney", "Created with Suno").
    r"\bmade (?:with|using) (?:midjourney|suno|synthesia|elevenlabs|heygen|runway)\b",
    r"\b(?:created|generated|rendered|produced) (?:with|using|by) "
    r"(?:midjourney|suno|synthesia|elevenlabs|heygen|runway)\b",
    r"\b(?:midjourney|synthesia|elevenlabs|heygen) (?:voice|generated|animation)\b",
    # Strict tagline / channel-formula patterns common to AI story farms.
    # The exact "Survival Was Never Meant to Be ..." tagline is the
    # signature of one specific AI story-farm channel — a real human
    # channel would not reuse it episode after episode.
    r"\bSurvival Was Never Meant to Be\b",
    # "[Era] Survival|Story|Chronicle|Tale | <anything>" — the pipe
    # separator after an era + storytelling noun is a strong AI-channel
    # template. The era word is required to keep "Catfish Survival Guide
    # | Tips and Tricks" and other legit pipe-separated titles safe.
    r"\b(?:prehistoric|ancient|medieval|stone[- ]?age|ice[- ]?age|"
    r"bronze[- ]?age|iron[- ]?age|viking|roman|egyptian|caveman)\s+"
    r"(?:survival|story|chronicle|tale)s?\b.*\|",
)

# SOFT patterns: common AI story-farm title shapes. A match here alone is
# not enough — it must combine with a weak corroborating signal in the
# description before we reject. This keeps real human content like a
# "Survival Story" vlog from getting nuked.
_AI_SOFT_PATTERNS = (
    # "[era] Survival Story" — the prehistoric/ancient/dystopian template.
    r"\b(?:prehistoric|ancient|medieval|dystopian|futuristic|"
    r"post[- ]apocalyptic|sci[- ]?fi)\s+survival\s+story\b",
    # "AI <topic> Story" — explicit AI-tagged story format.
    r"\bAI\s+\w+\s+story\b",
)

# Weak corroborating signals — only used to upgrade a soft hit to a reject.
_AI_WEAK_PATTERNS = (
    r"\bAI\b",
    r"\bvoiceover\b",
    r"\bnarrated\b",
    r"\bsynthetic voice\b",
    r"\btext[- ]to[- ]speech\b",
    r"\bTTS\b",
    r"\b(?:midjourney|suno|synthesia|elevenlabs|heygen|runway)\b",
    # Additional description corroborators for AI-narrated content.
    r"\btext[- ]?to[- ]?speech\b",
    r"\bTTS voice\b",
    r"\bsynthesized voice\b",
    r"\brobot voice\b",
    # Image-AI tool mentions (often listed in the description as "made with").
    r"\bstable diffusion\b",
    r"\bdall[- ]?e\b",
    r"\bflux\b",
    r"\bsdxl\b",
    # AI animation / artwork phrasing — too generic for a hard reject but
    # solid as a corroborating signal.
    r"\bAI animation\b",
    r"\bAI[- ]?generated images\b",
    r"\bAI artwork\b",
)

_AI_HARD_RE = re.compile("|".join(_AI_HARD_PATTERNS), re.IGNORECASE)
_AI_SOFT_RE = re.compile("|".join(_AI_SOFT_PATTERNS), re.IGNORECASE)
_AI_WEAK_RE = re.compile("|".join(_AI_WEAK_PATTERNS), re.IGNORECASE)


def _looks_ai_generated(item: dict[str, Any]) -> bool:
    """Detect AI-narrated / AI-animated long-form content via title + desc.

    Hard signals match alone. Soft signals (story-farm title shapes) only
    trigger when the description also contains a weak corroborating signal,
    avoiding false positives on real human "survival story" vlogs.
    """
    title = (item.get("title") or "")
    desc = (item.get("description") or "")[:400]
    haystack = f"{title}\n{desc}"
    if _AI_HARD_RE.search(haystack):
        return True
    if _AI_SOFT_RE.search(haystack) and _AI_WEAK_RE.search(desc):
        return True
    return False


def passes(
    item: dict[str, Any],
    page: "FacebookPage",
    settings: Any,
) -> tuple[bool, str | None]:
    """Return ``(True, None)`` when the candidate should be kept.

    Rejection reasons (second element when ``False``):
    - ``"too_short"``          — duration below ``YOUTUBE_MIN_DURATION_SECONDS``
    - ``"too_long"``           — duration above ``YOUTUBE_MAX_DURATION_SECONDS``
    - ``"livestream"``         — live or was-live stream
    - ``"private"``            — private / members-only / unavailable
    - ``"age_restricted"``     — age-gated content
    - ``"music_video"``        — looks like music compilation / DJ mix / playlist
    - ``"ai_generated"``       — title/desc indicates AI-narrated or AI-rendered content
    - ``"blocked_keyword:<w>"``— title or description contains a blocked keyword
    """
    duration = item.get("duration_seconds") or item.get("duration") or 0
    try:
        duration = int(float(duration))
    except (TypeError, ValueError):
        duration = 0

    min_dur: int = getattr(settings, "YOUTUBE_MIN_DURATION_SECONDS", 180)
    max_dur: int = getattr(settings, "YOUTUBE_MAX_DURATION_SECONDS", 1800)

    if duration > 0 and duration < min_dur:
        return False, "too_short"
    if duration > 0 and duration > max_dur:
        return False, "too_long"

    # Livestream / was-live detection.
    if item.get("is_live") or item.get("was_live"):
        return False, "livestream"
    live_status = item.get("live_status", "")
    if live_status in ("is_live", "is_upcoming", "was_live"):
        return False, "livestream"

    # Availability / privacy.
    availability = item.get("availability", "")
    if availability in ("private", "needs_auth", "subscriber_only"):
        return False, "private"
    if item.get("members_only"):
        return False, "private"

    # Age restriction.
    if item.get("age_limit") and int(item.get("age_limit", 0)) >= 18:
        return False, "age_restricted"

    # Music-compilation rejection (vlog / talk / interview pages don't want
    # DJ mixes, playlists, lyrics videos).
    if _looks_like_music(item):
        return False, "music_video"

    # AI-generated long-form content (synthetic narration, AI animation,
    # story-farm channels). Mirrors the music heuristic — title + first
    # ~400 chars of description, no LLM judge.
    if _looks_ai_generated(item):
        return False, "ai_generated"

    # Blocked keywords (case-insensitive match against title + description).
    blocked: list[str] = list(page.blocked_keywords or [])
    if blocked:
        haystack = " ".join(
            filter(None, [item.get("title", ""), item.get("description", "")])
        ).lower()
        for word in blocked:
            if word.lower() in haystack:
                return False, f"blocked_keyword:{word}"

    return True, None
